package com.imdb.analysis

import java.nio.file.{Files, Paths}

import org.apache.spark.sql.{Column, DataFrame, SparkSession}
import org.apache.spark.sql.functions._


object TopTitles {

  def constructTitlesDataFrame(ratings: DataFrame, titleMeta: DataFrame, minVotes: Int, titleType: String) : DataFrame = {
    ratings
      .filter(col("numVotes") > lit(minVotes))
      .join(titleMeta, Seq("tconst"))
      .select(ratings.columns.map(col) ++ List(col("titleType"), col("primaryTitle"), col("originalTitle")):_*)
      .filter(col("titleType") === lit(titleType))
  }

  def getTopNTitles(ratings: DataFrame, titles: DataFrame, topN: Int, titleType: String, minVotes: Int): DataFrame = {
    val averageNumVotes = ratings.agg(avg(col("numVotes"))).collect().head.getDouble(0)
    val rankedTitles = constructTitlesDataFrame(ratings, titles, minVotes, titleType)
      .withColumn("ranking", (col("numVotes") / lit(averageNumVotes)) * col("averageRating"))
    if(topN > 0) rankedTitles.sort(col("ranking").desc).limit(topN) else rankedTitles
  }

  def getAllTitlesForIds(allTitles: DataFrame, ids: List[String]): DataFrame= {
    allTitles
      .filter(col("titleId").isin(ids:_*))
      .groupBy(col("titleId").as("tconst"))
      .agg(collect_list(col("title")).as("alternateTitles"))
  }

  def getTopNPrincipalsForIds(principals: DataFrame, ids: List[String], topN: Int): DataFrame = {
    val principalsForIds = principals
      .filter(col("tconst").isin(ids:_*))
      .groupBy(col("nconst"))
      .count()
    if(topN > 0) principalsForIds.sort(desc("count")).limit(topN) else principalsForIds
  }

  val stringify = udf((vs: Seq[String]) => vs match {
    case null => null
    case _    => s"""[${vs.mkString(",")}]"""
  })


  def main(args: Array[String]): Unit = {

    if(args.length != 2){
      Console.err.println("Usage: TopTitles <data_folder> <output_folder> [<master_uri>]")
      Console.err.println("Missing input arg for data_folder or output_folder")
      sys.exit(-1)
    }

    val dataFolder = args(0)
    if(!Files.exists(Paths.get(dataFolder))){
      Console.err.println(s"Input data_folder $dataFolder does not exist ")
      sys.exit(-1)
    }

    val outputFolder = args(1)

    val sparkMaster = if(args.length == 3) args(1) else "local"

    implicit val spark = SparkSession.builder().master(sparkMaster).getOrCreate()


    try {
      //load all tsv files

      val titleBasics = TsvDataLoader.load(s"$dataFolder/title.basics.tsv")
      val titleRatings = TsvDataLoader.load(s"$dataFolder/title.ratings.tsv")
      val allTitles = TsvDataLoader.load(s"$dataFolder/title.akas.tsv")
      val names = TsvDataLoader.load(s"$dataFolder/name.basics.tsv")
      val principals = TsvDataLoader.load(s"$dataFolder/title.principals.tsv")

      val top20Movies = getTopNTitles(titleRatings, titleBasics, 20, "movie", 50)
      val top20Ids = top20Movies.select(col("tconst")).collect().map(_.getString(0)).toList
      val top20AllTitles = getAllTitlesForIds(allTitles, top20Ids)


      val allPrincipalsForTop20Titles = getTopNPrincipalsForIds(principals, top20Ids, 0)

      // top 10 most associated/credited principals based on top 20 movies
      allPrincipalsForTop20Titles.sort(desc("count")).limit(10).join(names, Seq("nconst"))
        .select(allPrincipalsForTop20Titles.columns.map(col) ++ List(col("primaryName")): _*)
        .sort(desc("count"))
        .write.csv(s"$outputFolder/top10CreditedPerson")

      /**
       * +---------+-----+-----------------+
       * |nconst   |count|primaryName      |
       * +---------+-----+-----------------+
       * |nm0634240|5    |Christopher Nolan|
       * |nm0000288|3    |Christian Bale   |
       * |nm0005212|3    |Ian McKellen     |
       * |nm0000704|3    |Elijah Wood      |
       * |nm0858799|3    |Emma Thomas      |
       * |nm0089217|3    |Orlando Bloom    |
       * |nm0333060|3    |David S. Goyer   |
       * |nm0746273|3    |Charles Roven    |
       * |nm0866058|3    |J.R.R. Tolkien   |
       * |nm0909638|3    |Fran Walsh       |
       * +---------+-----+-----------------+
       */


      //top 10 most known for names based on the top 20 movies
      names.join(allPrincipalsForTop20Titles, Seq("nconst"))
        .withColumn("knownForTitle", explode(split(col("knownForTitles"), ",")))
        .select(List(col("nconst"), col("primaryName"), col("knownForTitle")): _*)
        .filter(col("knownForTitle").isin(top20Ids: _*))
        .groupBy(col("nconst"))
        .agg(count(col("knownForTitle")).as("count"), first(col("primaryName")).as("name"))
        .sort(desc("count")).limit(10)
        .write.csv(s"$outputFolder/top10KnownPersons")

      /**
       * +---------+-----+-----------------+
       * |nconst   |count|name             |
       * +---------+-----+-----------------+
       * |nm0651614|4    |Barrie M. Osborne|
       * |nm0866058|3    |J.R.R. Tolkien   |
       * |nm0001877|3    |Hans Zimmer      |
       * |nm0005212|3    |Ian McKellen     |
       * |nm0000704|3    |Elijah Wood      |
       * |nm0002892|3    |Wally Pfister    |
       * |nm0809059|3    |Lee Smith        |
       * |nm0909638|3    |Fran Walsh       |
       * |nm0101991|3    |Philippa Boyens  |
       * |nm0915989|3    |Hugo Weaving     |
       * +---------+-----+-----------------+
       * It seems the producer link for Barrie Osborne linking him to The Matrix was missing in title.principals.tsv
       */

      top20Movies
        .join(top20AllTitles, Seq("tconst"))
        .drop("titleType", "originalTitle")
        .sort(desc("ranking"))
        .withColumn("alternateTitles", stringify(col("alternateTitles")))
        .write.csv(s"$outputFolder/top20Movies")

      /**
       * +---------+-------------+--------+-------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
       * |tconst   |averageRating|numVotes|primaryTitle                                     |ranking           |alternateTitles                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
       * +---------+-------------+--------+-------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
       * |tt0111161|9.3          |2136250 |The Shawshank Redemption                         |20703.47468032651 |[Rastegari dar Shawshank, Avain pakoon, Os Condenados de Shawshank, The Shawshank Redemption, Sueños de Libertad, Sueño de fuga, Sueños de libertad, Rita Hayworth - Avain pakoon, Um Sonho de Liberdade, A remény rabjai, The Shawshank Redemption, Bekstvo iz Šošenka, Die Verurteilten, Le ali della libertà, Nyckeln till frihet, Vykoupení z věznice Shawshank, Rita Hayworth - nyckel till flykten, Rita Hayworth - avain pakoon, Τελευταία έξοδος: Ρίτα Χέιγουορθ, Shôshanku no sora ni, Kaznilnica odrešitve, Sueño de libertad, De ontsnapping, Изкуплението Шоушенк, En verden udenfor, The Shawshank Redemption, Xiao shen ke de jiu shu, Homot Shel Tikva, Sueños de libertad, Iskupljenje u Shawshanku, Rita Hayworth -Avain pakoon, Pabegimas iš Šoušenko, Frihetens regn, The Shawshank Redemption, Shawshanki lunastus, Skazani na Shawshank, Nhà tù Shawshank, Esaretin Bedeli, Sueño de fuga, The Shawshank Redemption, Închisoarea îngerilor, Teleftaia exodos: 'Rita Hayworth', Cadena perpètua, The Shawshank Redemption, Les évadés, The Shawshank Redemption, À l'ombre de Shawshank, Vykúpenie z väznice Shawshank, Cadena perpetua, The Prisoner, Sueños de fuga, The Shawshank Redemption, Побег из Шоушенка, Shawshank Redemption - Avain pakoon, Die Verurteilten, Sueños de fuga, Gaqceva shoushenkidan, Втеча з Шоушенка, Shoushenkden Qacish, The Shawshank Redemption, Rita Hayworth and Shawshank Redemption]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
       * |tt0468569|9.0          |2100704 |The Dark Knight                                  |19702.239185274448|[The Dark Knight, Temný Rytier, The Dark Knight, The Dark Knight, Vitez tame, Yön ritari, The Dark Knight, Ο σκοτεινός ιππότης, Batman - El caballero de la noche, Ky si bóng dêm, The Dark Knight, Untitled Batman Begins Sequel, Kara Sövalye, Cavalerul negru, Temný rytíř, Bianfu xia - Heiye zhi shen, Тёмный рыцарь, Темний лицар, Winter Green, The Dark Knight, Batman: O Cavaleiro das Trevas, Iravu Kavalan, Черният рицар, The Dark Knight: Le chevalier noir, Batman Begins 2, The Dark Knight, Kalorësi i Errësirës, Le chevalier noir, O Cavaleiro das Trevas, The Dark Knight, Mračni vitez, Pimeduse rüütel, El caballero oscuro, Mroczny rycerz, Shavi Raindi, A sötét lovag, O skoteinos ippotis, Vitez teme, Tamsos riteris, Dâku naito, Batman: Atsawinrattikan, Batman - El caballero de la noche, Batman 2 - El caballero de la noche, Batman: El Caballero de la Noche, El cavaller fosc, The Dark Knight: The IMAX Experience, The Dark Knight, The Dark Knight, Rökkurriddarinn, Batman: El caballero de la noche, The Dark Knight, Il cavaliere oscuro, Rory's First Kiss, Batman: The Dark Knight]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
       * |tt1375666|8.8          |1873575 |Inception                                        |17181.535358180718|[Origine, Începutul, Початок, Algus, Početak, Chakravuyh, Počátek, Οι ονειροπαγιδευτές, Eredet, Hat'hala, El origen, El origen, Inception, Генезис, Baslangiç, Inception, El origen, Inception, Начало, Izvor, Jit Phi Khat Lôk, Dasatskisi, Pirmsakums, Inception, Oliver's Arrow, Počiatok, Inception, Origen, Inception, Inception, A Origem, Inception, Talghin, Inception, Inception, Pradžia, Inception, El origen, Inception: The IMAX Experience, Početak, A Origem, El origen, Inception, El origen, Incepcja, Inception, Inception, Inception]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
       * |tt0137523|8.8          |1707792 |Fight Club                                       |15661.229805275032|[Fight Club, Fight club - Sala de lupte, Бойцовский клуб, Fight Club, Fight Club, Fight Club, Harcosok klubja, Fight Club, Döyüshçü Klubu, Clube da Luta, Fight Club, Fight Club, El club de la pelea, Fight Club, Klub golih pesti, Боен клуб, Klub boraca, Nadi alghetal, Kaklusklubi, Fight Club, Podziemny krąg, Бiйцiвський клуб, Fight Club, Fight Club, Fight Club, Mo'adon Krav, Fight Club, Borechki Klub, El club de la lucha, Fight Club, El club de la pelea, Klub Bitkárov, Kovos klubas, El club de la pelea, Bashgah-e moshtzani, Clube de Combate, Klub rváčů, Fight Club, Borilački klub, Dövüs Kulübü]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
       * |tt0110912|8.9          |1676666 |Pulp Fiction                                     |15550.515109631742|[Tiempos violentos, Dastan-e aame pasand, Pulp Fiction, Pulp Fiction, Tiempos violentos, Pulp Fiction, Tiempos violentos, Кримiнальне чтиво, Makulatura, Криминале, Pulp Fiction, Pulp Fiction, Pulp Fiction, Pulp Fiction, Petparačke priče, Šund, Pulp Fiction, Tarinoita väkivallasta, Tiempos violentos, Pulp Fiction, Pulp Fiction, Pulp Fiction, Pulp Fiction, Pulp Fiction, Pulp Fiction: Historky z podsvetia, Pulp Fiction, Pulp Fiction, Pulp Fiction: Historky z podsvětí, Black Mask, Fiction pulpeuse, Lubene, Pulp Fiction, Pulp Fiction, Ponyvaregény, Pulp Fiction: Tempo de Violência, Pulp Fiction, Pulp Fiction: Tiempos violentos, Pulp Fiction: Tarinoita väkivallasta, Pulp Fiction, Bulvarinis skaitalas, Pulp Fiction, Ucuz Roman, Pulp Fiction, Kriminal Qirayet, Sifrut Zolla, Криминальное чтиво, Pulp Fiction, Pakleni šund]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
       * |tt0109830|8.8          |1644114 |Forrest Gump                                     |15077.27356731379 |[Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Φόρεστ Γκαμπ, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Forrest Gump, Форест Гъмп, Forest Gamp, Форрест Гамп, Forrest Qamp, Forrest Gump: The IMAX Experience, Forestas Gampas, Forrest Gump, Forrest Gump: O Contador de Histórias, Forrest Gump, Форрест Гамп]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
       * |tt0167260|8.9          |1519190 |The Lord of the Rings: The Return of the King    |14089.977997646189|[Seyed alkhavatem 3: Awdat almalek, O Senhor dos Anéis - O Regresso do Rei, El senyor dels anells: El retorn del rei, Властелин колец: Возвращение короля, Le seigneur des anneaux: Le retour du roi, Ο άρχοντας των δαχτυλιδιών: Η επιστροφή του βασιλιά, The Lord of the Rings: The Return of the King, Taru sormusten herrasta: Kuninkaan paluu, Der Herr der Ringe: Die Rückkehr des Königs, El señor de los anillos: El retorno del rey, Arbab-e halgheha 3: Bazgasht-e padeshah, Ringenes herre: Kongen vender tilbage, Володар перснiв: Повернення короля, The Lord of the Rings: The Return of the King, The Lord of the Rings: The Return of the King, Gospodar prstenova - Povratak kralja, Pán prsteňov: Návrat kráľa, O arhontas ton dahtylidion: I epistrofi tou vasilia, In de ban van de ring: De terugkeer van de koning, Ringenes herre: Atter en konge, Stapanul Inelelor: Intoarcerea Regelui, The Lord of the Rings: The Return of the King, Kryezoti i Unazave: Kthimi i Mbretit, Властелинът на пръстените: Завръщането на краля, Gospodar prstenova: Povratak kralja, El señor de los anillos: El retorno del rey, Pán prstenů: Návrat krále, A Gyűrűk Ura: A király visszatér, Il Signore degli Anelli - Il ritorno del re, The Return of the King, Taru Sormusten Herrasta - Kuninkaan paluu, Rôdo obu za ringu - Ô no kikan, The Lord of the Rings: The Return of the King, Gospodarot na prstenite: Vrakjanjeto na kralot, The Lord of the Rings: The Return of the King, O Senhor dos Anéis: O Retorno do Rei, Hringadróttinssaga: Hilmir snýr heim, Sõrmuste isand: Kuninga tagasitulek, Le seigneur des anneaux - Le retour du roi, El señor de los anillos: El retorno del rey, Žiedu Valdovas: Karaliaus sugrižimas, El señor de los anillos - El retorno del rey, El señor de los anillos: El retorno del rey, Sagan om konungens återkomst, Yüzüklerin Efendisi: Kralin Dönüsü, Władca pierścieni: Powrót króla, Sar Hatabaot: Shivat Hamelekh', Gospodar prstanov: Kraljeva vrnitev, Sagan om konungens återkomst]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
       * |tt0120737|8.8          |1534822 |The Lord of the Rings: The Fellowship of the Ring|14075.016191779698|[The Lord of the Rings: The Fellowship of the Ring, Le seigneur des anneaux - La communauté de l'anneau, Stapînul inelelor: Fratia inelului, Властелин колец: Братство кольца, Il Signore degli Anelli - La compagnia dell'Anello, Pán prsteňov: Spoločenstvo Prsteňa, Sõrmuste isand: Sõrmuse vennaskond, Stapânul Inelelor: Fratia Inelului, Sagan om ringen: Härskarringen, Yüzüklerin Efendisi: Yüzük Kardesligi, Hringadróttinssaga: Föruneyti hringsins, Ringenes herre: Eventyret om ringen, The Lord of the Rings: The Fellowship of the Ring, The Lord of the Rings: The Fellowship of the Ring, El señor de los anillos: La comunidad del anillo, Lord of the Rings, Gospodarot na prstenite: Druzhinata na prstenot, In de ban van de ring: De reisgenoten, The Lord of the Rings: The Fellowship of the Ring, O arhontas ton dahtylidion: I syntrofia tou dahtylidiou, Władca pierścieni: Drużyna Pierścienia, Žiedu Valdovas: Žiedo brolija, A Gyűrűk Ura: A gyűrű szövetsége, Taru sormusten herrasta: Sormuksen ritarit, Le seigneur des anneaux: La communauté de l'anneau, Arbab-e halgheha: Yaran-e halgheh, Rôdo obu za ringu, O Senhor dos Anéis - A Irmandade do Anel, El señor de los anillos: La comunidad del anillo, The Lord of the Rings: The Fellowship of the Ring, Ringenes herre: Ringens brorskap, O Senhor dos Anéis: A Sociedade do Anel, The Fellowship of the Ring, Gospodar prstenova: Prstenova družina, Seyyed alkhavatem: Sohbat alkhatam, Sagan om ringen, Pán prstenů: Společenstvo prstenu, El señor de los anillos: La comunidad del anillo, El senyor dels anells: La germandat de l'anell, The Lord of the Rings: The Fellowship of the Ring, El señor de los anillos: La comunidad del anillo, Властелинът на пръстените: Задругата на пръстена, Bechdebis mbrdzanebeli: Bechdis sadzmo, El senyor dels anells: La comunitat de l'anell, Sar HaTabaot: Achvat HaTabaat, Gospodar prstenova - Družina prstena, Володар перснiв: Хранителi персня, El señor de los anillos: La comunidad del anillo, Der Herr der Ringe: Die Gefährten, Sagan om ringen: Härskarringen, The Lord of the Rings: The Fellowship of the Ring, Ο άρχοντας των δαχτυλιδιών: Η συντροφιά του δαχτυλιδιού, Kryezoti i Unazave: Besëlidhja e Unazës, The Lord of the Rings: The Fellowship of the Ring, The Lord of the Rings: The Fellowship of the Ring, The Lord of the Rings: The Fellowship of the Ring: The Motion Picture, Gospodar prstanov: Bratovscina prstana]                                                                                                       |
       * |tt0068646|9.2          |1466689 |The Godfather                                    |14061.578557229761|[Natlimama, De peetvader, Mario Puzo's The Godfather, Der Pate, Крёстный отец, El padrino, The Godfather, Le parrain, Krstný Otec, Krikštatevis, The Godfather, Gudfadern, Ristiisa, The Godfather, Godfather, Ojciec chrzestny, Der Pate, O nonos, The Godfather, Mario Puzo's The Godfather, El Padrino, A keresztapa, De peetvader, El padrí, O Poderoso Chefão, Кръстникът, Il padrino, The Godfather, El padrino, Guðfaðirinn, Daeboo, Goddofâzâ, Kmotr, Der Pate, Boter, The Godfather, Kumbari, Kum, Pedar khandeh, Le parrain, Хрещений батько, Godfather, Baba, Gudfaren, Kum, Hasandak, Крёстный отец, The Godfather, El padrino, El Padrino, Al-arraab, Ο νονός, O Padrinho, Bo Gia, Kmotr, The Godfather, El padrino, Nasul, Kum, El Padrino, Krstný Otec, Kummisetä]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
       * |tt0133093|8.7          |1538461 |The Matrix                                       |13948.064892805438|[Matrix, Matrix, Matrix, Matrikss, Matrica, Matrix, Matriks, The Matrix, Matorikkusu, Matrix, The Matrix, The Matrix, The Matrix, La matriz, Matrix, Matrix, Matrix, Maatriks, Matrix, The Matrix, Matrix, The Matrix, Fylkið, Matrix, Matrix, The Matrix, Matrix, Matrix, Матрицата, Matrix, Матрикс, Matrix, Matrica, The Matrix, Matrix, Matrix, La matrice, Matrix, Mátrix, Matrix, Matrix, Matrix, Матриця, The Matrix, Матрица, Matrix]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
       * |tt0167261|8.7          |1374149 |The Lord of the Rings: The Two Towers            |12458.3719862796  |[Arbab-e halgheha 2: Do borj, Володар перснiв: Двi вежi, The Lord of the Rings: The Two Towers, Ringenes herre: De to tårne, Le seigneur des anneaux: Les deux tours, Sõrmuste isand: Kaks kantsi, O Senhor dos Anéis - As Duas Torres, A Gyűrűk Ura: A két torony, Hringadróttinssaga: Tveggja turna tal, Rôdo obu za ringu - Futatsu no tô, Stapânul inelelor: Cele doua turnuri, Władca pierścieni: Dwie wieże, Sagan om de två tornen, The Lord of the Rings: The Two Towers, Pán prstenů: Dvě věže, El señor de los anillos: Las dos torres, In de ban van de ring: De twee torens, O arhontas ton dahtylidion: Oi dyo pyrgoi, The Lord of the Rings: The Two Towers, Ο άρχοντας των δαχτυλιδιών: Οι δύο πύργοι, Gospodar prstanov: stolpa, O Senhor dos Anéis: As Duas Torres, Taru sormusten herrasta: Kaksi tornia, The Two Towers, Властелин колец: Две крепости, El señor de los anillos: Las dos torres, Ringenes herre: To tårn, Sagan om de två tornen - härskarringen, Властелинът на пръстените: Двете кули, El señor de los anillos: Las dos torres, Il Signore degli Anelli - Le due torri, Banjieui jewang du gaeeui tab, Le seigneur des anneaux - Les deux tours, Gospodar prstenova - Dve kule, El señor de los anillos: Las dos torres, The Lord of the Rings: The Two Towers, Sar Hatabaot: Shnei Hatzri'kh'im, Yüzüklerin Efendisi: Iki Kule, El señor de los anillos: Las dos torres, Gospodarot na prstenite: Dvete kuli, Kryezoti i Unazave: Dy Kullat, Der Herr der Ringe: Die zwei Türme, El señor de los anillos: Las dos torres, Seyed alkhavatem 2, Pán prsteňov: Dve veže, The Lord of the Rings: The Two Towers, Žiedu Valdovas: Dvi tvirtoves, Gospodar prstenova: Dvije kule, El senyor dels anells: Les dues torres]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
       * |tt1345836|8.4          |1407521 |The Dark Knight Rises                            |12320.898632209437|[Vzpon Viteza teme, Tamsos riterio sugrižimas, Batman: El caballero de la noche asciende, Dâku naito raijingu, The Dark Knight Rises, Arkham, Tumsais bruninieks atgriezas, The Dark Knight Rises, Gotham, Návrat Temného rytiera, Черният рицар: Възраждане, Batman 3, Uspon Mračnog viteza, Batman: El caballero de la noche asciende, The Dark Knight Rises, A sötét lovag: Felemelkedés, Ky Si Bong Dem Troi Day, The Dark Knight Rises, The Dark Knight Rises, Shavi Raindis Agzeveba, O Cavaleiro das Trevas Renasce, Vitez tame: Povratak, El caballero oscuro: La leyenda renace, The Dark Knight Rises: The IMAX Experience, Kara Sövalye Yükseliyor, Vitez tame: Povratak, L'ascension du chevalier noir, The Dark Knight Rises, Bianfu xia: Ye shen qiyi, Dakeu naiteu raijeu, Pinfuk haap: Ye san heiyi, Bianfu xia: Hei'an qishi jueqi, O skoteinos ippotis: I epistrofi, Ο σκοτεινός ιππότης: Η επιστροφή, Pimeduse rüütli taastulek, The Dark Knight Rises, Aliyato shel ha'abir ha'af'el, Batman: El caballero de la noche asciende, Mroczny Rycerz powstaje, Hei'an qishi: Liming shengqi, Batman: O Cavaleiro das Trevas Ressurge, The Dark Knight Rises, Batman: El caballero de la noche asciende, Batman 3: Dark knight ki vijay, Тёмный рыцарь: Возрождение легенды, T.D.K.R., Batman: El caballero de la noche asciende, Yön Ritarin paluu, El cavaller fosc: La llegenda reneix, Cavalerul negru: Legenda renaste, Темний лицар повертаеться, Temný rytíř povstal, Il cavaliere oscuro - Il ritorno, Magnus Rex]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
       * |tt0816692|8.6          |1330022 |Interstellar                                     |11919.704561731207|[Interstellar, Yildizlararasi, Interstellar: Calatorind prin univers, Iнтeрстеллар, Udhëtimi Ndëryjor, Interstellar, Du Hành Liên Sao, Interstelari, Interstellar, Interestelar, Interstellar, Flora's Letter, Interstellar, Xing Ji Chuan Yue, Интерстеллар, Interestelar, Interstellar, Interstellaire, Untitled Steven Spielberg Space Project, Интерстелар, Interstellar, Interestelar, Interstellar, Interstellar, Interestelar, Csillagok között, Interestelar, Interestelar, Medzvezdje, Tähtedevaheline, Bein kokhavim, Međuzvezdani, Interstellar, Interestelar, Ulduzlararasi, Interstellar, Interstellar, Tarp žvaigždžiu, Interstellar]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
       * |tt0114369|8.6          |1312822 |Se7en                                            |11765.557548778206|[Seven: Os Sete Crimes Capitais, Seven, Seven - 7 Pecados Mortais, Se7en, Семь, The Seven Deadly Sins, Septyni, Seitsemän, Seven, Sieben, Pecados capitales, Седем, Seven, Pecados capitales, Yedi, Yeddi, Seven, Hetedik, Sieben, Seven, Сiм, Sedam, Sedm, Seven, Los siete pecados capitales, Shvidi, Sedem, Se7en, Sept, Epta, Haft, Se7en, Se7en: pecados capitales, Seven, Se7en, Seven, Sedam, Seven, los siete pecados capitales, Se7en, Seven, Seven, Sete Pecados Mortais, Seitse, Sep7, Se7en, Sedem, Sebun, Siedem, Seven]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
       * |tt0172495|8.5          |1233159 |Gladiator                                        |10923.107753798922|[Gladiator, Gladiador, Gladiator, Monomahos, Гладиатор, Gladiator, Gladiator, Gladiador, Gladijator, The Gladiators, Gladyatör, Gladiator, Gladiator, Gladiatorius, Gladiatorul, Gladiaattori, Gladiator (El gladiador), Gladiátor, Gladiator, Il gladiatore, Gladiator, Gladiátor, Гладiатор, Gladiador, Skylmingaþrællinn, Gladiador, Gladiator, Gladiator, Gladiador, Gladiador, Gladiator, Gladiator, Gladiator, Gladiator, Gladiator, Gladiator - Special Edition, Gladiaator, Гладиатор, Gladiatoren, Gladiátor, Gladijator, Gladiator, Gladiador, Gladiator, Gladiator, Vijeta, Gladiateur, Gladiador, Μονομάχος]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
       * |tt1853728|8.4          |1236579 |Django Unchained                                 |10824.537971169819|[Zencirsiz Canqo, Django Unchained, Django Libertado, Django Unchained, Django, ο τιμωρός, Django elszabadul, Django sin cadenas, Odbjegli Django, Django Unchained, Nespoutaný Django, Vabastatud Django, Джанго освобожденный, Jango-ye raha shode, Django Khot Khon Dan Theuoen, Django sin cadenas, Django déchaîné, Đangova osveta, Django Unchained, Django sin cadenas, Django Unchained, Django Unchained, Django Unchained, Django sin cadenas, Django, o timoros, Django sin cadenas, Django desencadenat, Django Unchained, Джанго без окови, Django Unchained, Django sin cadenas, Django desencadenado, Джанго вiльний, Django Livre, Django Unchained, Django Lelo Ma'atzorim, Zincirsiz, Django sin cadenas, Django, Django Tsunagarezaru Mono, Ištrukęs Džango, Django dezlantuit, Django brez okovov, Hành Trình Django]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
       * |tt0102926|8.6          |1157033 |The Silence of the Lambs                         |10369.370978956396|[The Silence of the Lambs, The Silence of the Lambs, Η σιωπή των αμνών, The Silence of the Lambs, O Silêncio dos Inocentes, När lammen tystnar, Sokout-e bareha, Le silence des agneaux, El silencio de los inocentes, När lammen tystnar, Молчание ягнят, Le silence des agneaux, Kad jaganjci utihnu, Ko jagenjčki obmolknejo, El silenci dels anyells, Das Schweigen der Lämmer, Mlčanie jahniat, Kravta dumili, The Silence of the Lambs, Uhrilampaat, Silence of the Lambs, Voonakeste vaikimine, Nattsvermeren, Kuzularin Sessizligi, Kad jaganjci utihnu, The Silence of the Lambs, Мълчанието на агнетата, Молчание ягнят, El silencio de los inocentes, Su Im Lang Cua Bay Cuu, Somt alhemlan, The Silence of the Lambs, Milczenie owiec, I siopi ton amnon, Il silenzio degli innocenti, El silencio de los inocentes, O Silêncio dos Inocentes, Mlčení jehňátek, El silencio de los inocentes, Mlčanie Jahniat, A bárányok hallgatnak, The Silence of the Lambs, El silencio de los corderos, The Silence of the Lambs, Mlčení jehňátek, Das Schweigen der Lämmer, Hitsujitachi no Chinmoku, De schreeuw van het lam, Tacerea mieilor, Avineliu tylejimas, El silencio de los inocentes, Ondskabens øjne, Мовчання ягнят, El silencio de los inocentes]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
       * |tt0372784|8.2          |1212545 |Batman Begins                                    |10361.435617448591|[Batman: na začetku, Бетмен: Початок, Batman - El inicio, Batman Inicia, Batman Begins: The IMAX Experience, Batman - Początek, Batman: El comienzo, Batman Begins, Batman inicia, Batman inicia, Μπάτμαν: Η αρχή, Batman inicia, Batman Begins, Batman Basliyor, Batman - Inceputuri, Batman 5, Batman inicia, Batman Begins, Batman comienza, Batman začíná, Batman inicia, Batman - O Início, Batman Begins, Бэтмен: Начало, Betmen počinje, Batman: Kezdődik!, Netopierí muž začína, Betmenas: Pradžia, Batman Begins, Batman Begins, Party In Fresno, Батман в началото, Batman: Početak, Batman Begins, Batman: Le commencement, Batman Begins, Batman začína, Batman alustab, The Intimidation Game, Batman Begins, Batman Begins, Batman Begins, Batman: Intimidation, Batman Begins]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
       * |tt0108052|8.9          |1108757 |Schindler's List                                 |10283.349505154849|[Schindler's List, Fehrest-e Schindler, Steven Spielberg's Schindler's List, Schindlerův seznam, La liste de Schindler, La llista de Schindler, Shindorâ no risuto, La lista de Schindler, La lista de Schindler, La lista de Schindler, Schindlerjev seznam, Schindlers Liste, La lista de Schindler, Шиндлеровата Листа, A Lista de Schindler, Schindlers Liste, Šindlerov Zoznam, Shindleris sia, La lista de Schindler, Ban danh sách cua Schindler, Schindler'in Listesi, Schindler's List, Списъкът на Шиндлер, Schindler's List, La lista de Schindler, Schindlers lista, Schindlerova lista, Schindlers liste, Šindlerio sąrašas, Schindler's List, Η λίστα του Σίντλερ, Список Шиндлера, Schindleri nimekiri, Schindler listája, I lista tou Schindler, Šindlerova lista, La lista de Schindler, Lista Schindlera, Lista lui Schindler, Schindler's List, Shindlerin Siyahisi, Schindlers liste, Schindlerin lista, Список Шиндлера, La liste de Schindler, Schindler's List, Schindler's List - La lista di Schindler, Reshimut Schindler, A Lista de Schindler]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
       * |tt0076759|8.6          |1138001 |Star Wars: Episode IV - A New Hope               |10198.805516716771|[O polemos ton astron, La guerra de las estrellas, Star Wars: A New Hope, Star Wars, Zvezdani ratovi: Nova nada, Hviezdne vojny IV: Nová nádej, Star Wars: A New Hope, Star Wars - Episode IV: Eine neue Hoffnung, La guerre des étoiles - Un nouvel éspoir, The Star Wars: From the Adventures of Luke Starkiller, Hviezdne vojny 4: Nová nádej, Star Wars, Episódio IV: Uma Nova Esperança, Star Wars: Episode IV - A New Hope, Hvězdné války IV: Nová naděje, Tähtien sota, Star Wars: Uusi toivo, La guerra de las galaxias, Adventures of the Starkiller: Episode 1 - The Star Wars, Žvaigždžiu karai, Gwiezdne wojny, La guerra de las galaxias, Ratovi zvijezda IV: Nova nada, Gwiezdne wojny, czesc IV: Nowa nadzieja, Vojna zvezd: Epizoda IV - Novo upanje, Razboiul stelelor, Star Wars IV - Una nuova speranza, La guerra de las galaxias, Star Wars: Episode IV - Et nytt håp, Stjernekrigen, A Guerra das Estrelas, A New Hope, Sutâ wôzu episoddo 4: Aratanaru kibô, Star Wars: Episodio IV - Una nuova speranza, Star Wars - Stjernekrigen, Războiul Stelelor - Episodul IV: O nouă speranţă, Guerra nas Estrelas, La guerra de las galaxias, Ο πόλεμος των άστρων, Star Wars: Episod IV - Nytt hopp, La guerra de las galaxias, The Star Wars, Star wars: Osa IV - Uus lootus, La guerra de las galaxias, Star Wars, O polemos ton astron: Mia nea elpida, Yildiz Savaslari: Bölüm IV - Yeni Bir Umut, La guerra de las galaxias, Stjärnornas krig, Звёздные войны. Эпизод 4: Новая надежда, Ratovi zvezda - Nova nada, Hvězdné války IV: Nová naděje, Star Wars: Episode IV - A New Hope, Star Wars: Episode IV - A New Hope, Star Wars, Star wars: Épisode IV, la guerre des étoiles, Междузвездни войни: Епизод IV - Нова Надежда, Războiul Stelelor: Ediţie specială, Jang-e setarehha, Star Wars IV. rész - Egy új remény, La guerra de las galaxias, Ratovi zvijezda, Stjörnustríð, The Adventures of Luke Starkiller as Taken from the 'Journal of the Whills': Saga I - Star Wars, Csillagok háborúja, Star Wars: Episodio IV - Una nueva esperanza, Звёздные войны. Эпизод 4: Новая надежда, Yildiz Savaslari, La guerre des étoiles, Tähtede sõda, Star Wars: Episode IV - A New Hope, Krieg der Sterne, Stjärnornas krig, La guerre des étoiles, Guerre stellari, Звёздные войны, The War of the World, La guerra de las galaxias, Hviezdne vojny IV: Nová nádej, Star Wars: Episode IV - A New Hope, Зорянi вiйни: Епiзод 4 - Нова надiя, Star Wars: Episodi IV - Uusi toivo, Star Wars: Episódio IV - Uma Nova Esperança, Star Wars: Episodio IV - Una nueva esperanza]|
       * +---------+-------------+--------+-------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
       */
    }
    finally {
      spark.stop()
    }

  }

}
